typography_spectrum: 0.93049
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.3212698728311807
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.39848
analytics:
  google: null
  facebook: null
  twitter: null
name: Cutler Weddings
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Cutler Weddings
purpose: []
